version: 2
jobs:
  build:
    docker:
      - image: node:carbon
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: apt-get update && apt-get install -y cmake
      - run: npm install --unsafe-perm
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
